#4 Wiki Editing in tree structure - toggle button
Neo-Atlas/humhub_wiki pull request #5
Opened 2024-12-21 13:01 UTC by vidhyasagargm

Hello @marius-meissner,
TO solve the issue #3, A toggle button has been implemented in order to toggle between enabling and disabling editing the wiki tree structure. The code is ready for review.

2024-12-30 12:37 UTC, marius-meissner requested changes
Thanks for the PR.
Nice test coverage btw. :+1: 

Changes have been deployed to the staging system successfully.
@TobiNeo Please have a look from your side as well.

2024-12-30 12:37 UTC, marius-meissner commented on messages/de/base.php
> +    'Enable wiki tree editing' => 'wiki tree Bearbeitung aktivieren',
```suggestion
    'Disable wiki tree editing' => 'Bearbeitung der Seitenhierachie deaktivieren',
    'Enable wiki tree editing' => 'earbeitung der Seitenhierachie aktivieren',
```

2024-12-30 12:37 UTC, marius-meissner commented on views/overview/list-categories.php
> +                    <?php endif; ?>
The toggle buttons already take up a lot of space. Therefore, please nest them in a dropdown. You can call them options, for example.

2025-01-04 19:44 UTC, vidhyasagargm commented
Hello @marius-meissner ,
a dropdown menu has been added. The code is ready for review.

2025-01-05 17:31 UTC, marius-meissner requested changes
Changes have been successfully deployed to staging.
@TobiNeo Please have a look from your side as well.

Looks good from my side, one tiny suggestion.

2025-01-05 17:31 UTC, marius-meissner commented on views/overview/list-categories.php
> +                        </button>
Looks good. What about adding an icon?
Maybe a gear wheel:
```html
<i class="fa fa-cog"></i>
```

2025-01-06 09:57 UTC, vidhyasagargm commented
Hello @marius-meissner ,
A gear wheel icon has been added into the options button. The code is ready for review.

2025-01-13 13:47 UTC, TobiNeo commented
Thanks Vidhya. As discussed, I will prepare your next task ASAP- probably today or tomorrow.


> Changes have been successfully deployed to staging.
> @TobiNeo Please have a look from your side as well.

@marius-meissner:
![grafik](https://github.com/user-attachments/assets/6f4cd24e-62ed-4edb-ad49-c5914749101d)
Tried to check it in the system. This is how staging looks for me right now. Am I checking the wrong position?..^^

2025-01-13 13:50 UTC, vidhyasagargm commented
> @marius-meissner: ![grafik](https://private-user-images.githubusercontent.com/114566202/402559475-6f4cd24e-62ed-4edb-ad49-c5914749101d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3NzY0NzksIm5iZiI6MTczNjc3NjE3OSwicGF0aCI6Ii8xMTQ1NjYyMDIvNDAyNTU5NDc1LTZmNGNkMjRlLTYyZWQtNGVkYi1hZDQ5LWM1OTE0NzQ5MTAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExM1QxMzQ5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTFmOTRjODQyNWFhMDk2YmY4OTJlNmQxNTY1MDg4NDg0NWNjOGI4ODA5NDQ1YzQwMWIwYzE1ZmZhNWNlODA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uw2bI6712WxSU2U1tFHbsPaq8hVtW8024o-4UMNzyrE) Tried to check it in the system. This is how staging looks for me right now. Am I checking the wrong position?..^^

I believe you have to be a moderator or admin to get the toggle edit option.

2025-01-13 14:08 UTC, TobiNeo commented
> > @marius-meissner: ![grafik](https://private-user-images.githubusercontent.com/114566202/402559475-6f4cd24e-62ed-4edb-ad49-c5914749101d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3NzY0NzksIm5iZiI6MTczNjc3NjE3OSwicGF0aCI6Ii8xMTQ1NjYyMDIvNDAyNTU5NDc1LTZmNGNkMjRlLTYyZWQtNGVkYi1hZDQ5LWM1OTE0NzQ5MTAxZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDExM1QxMzQ5MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OTFmOTRjODQyNWFhMDk2YmY4OTJlNmQxNTY1MDg4NDg0NWNjOGI4ODA5NDQ1YzQwMWIwYzE1ZmZhNWNlODA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.uw2bI6712WxSU2U1tFHbsPaq8hVtW8024o-4UMNzyrE) Tried to check it in the system. This is how staging looks for me right now. Am I checking the wrong position?..^^
> 
> @TobiNeo I believe you have to be a moderator or admin to get the toggle edit option.

Hi Vidhya,
Right, that was indeed the issue. Global Admin rights are not enough, you need to be space admin/mod again - then it shows up:
![grafik](https://github.com/user-attachments/assets/5133a457-08e3-4177-b40f-a99d04faa739)


Looks good from my perspective :)

2025-01-17 11:28 UTC, marius-meissner approved these changes
LGTM.
Changes will be deployed soon to prod. system.

@vidhyasagargm Please create a upstream PR. Maybe some coordination is required, as the PR is based on your other PR https://github.com/humhub/wiki/pull/357.

2025-01-17 11:29 UTC, merged